# Generated by Django 5.2.10 on 2026-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accreditation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(max_length=60),
        ),
    ]
